CREATE TABLE CLIENTE (

ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (60) NOT NULL, 
CPF VARCHAR (11) NOT NULL,
DT_CONTRATO DATE NOT NULL, 
VL_SALARIO DECIMAL(19,2),
VL_PATRIMONIO DECIMAL(19,2)


)