CREATE TABLE PROPOSTA (

ID INTEGER PRIMARY KEY AUTO_INCREMENT,
DT_CONTRATACAO DATE NOT NULL, 
QTD_PARCELA INTEGER (02) NOT NULL,
VLR_CONTRATADO DECIMAL (19,2) NOT NULL,
TX_JUROS DECIMAL (5,2) NOT NULL

)